[tools]
luau-lsp = "JohnnyMorganz/luau-lsp@1.27.0"
selene = "Kampfkarren/selene@0.26.1"
stylua = "johnnymorganz/stylua@0.19.1"

rojo = "rojo-rbx/rojo@7.3.0"

wally = "UpliftGames/wally@0.3.2"
wally-package-types = "JohnnyMorganz/wally-package-types@1.3.0"